services:
  # Config watcher service
  watcher:
    container_name: config_watcher
    image: ${DOCKER_REGISTRY:-local}/watcher:${TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-1.0.0}
        APP_ENV: ${APP_ENV:-production}
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
    environment:
      - REPO_URL=${REPO_URL:-"https://github.com/nuniesmith/nginx.git"}
      - BRANCH=${BRANCH:-main}
      - WATCH_INTERVAL=${WATCH_INTERVAL:-60}
      - USE_DOCKER_COMPOSE=${USE_DOCKER_COMPOSE:-false}
      - AUTO_FIX=${AUTO_FIX:-true}
      - FIX_PERMISSIONS=${FIX_PERMISSIONS:-true}
      - MONITOR_LOGS=${MONITOR_LOGS:-true}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY:-}
      - CONFIG_DIR=/app/config
      - STARTUP_GRACE_PERIOD=${STARTUP_GRACE_PERIOD:-30s}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config_data:/app/config
    restart: unless-stopped
    healthcheck:
      test: CMD /usr/local/bin/healthcheck.sh
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  config_data:
    driver: local